unit c_DBTypes;

interface

const
  SysSP_MsgF = 'MsgF';
  SysSP_Msg = 'Msg';
  SysSP_SP_ID = 'SP_SP_ID';
  SysSP_ID = 'SP_ID';

  SP_TEXT_DE  = 'SP_Text_DE';
  SP_TEXT_Ori = 'SP_Text_Ori';

  GU_REFKEY = 'GU_REFKEY';
  GU_TABELLE = 'GU_TABELLE';
  GU_GUID    = 'GU_GUID';
  GU_INSERT  = 'GU_INSERT';
  GU_BE_ID  = 'GU_BE_ID';
  GU_UPDATE  = 'GU_UPDATE';
  GU_USERID_INSERT = 'GU_USERID_INSERT';
  GU_USERID_UPDATE = 'GU_USERID_UPDATE';
  GU_REFID = 'GU_REFID';
  GU_DELETE = 'GU_DELETE';

  IT_GRUPPE = 'IT_GRUPPE';
  IT_INDEX = 'IT_INDEX';

  SL_GUID = 'SL_GUID';
  SL_TEXT = 'SL_TEXT';
  SL_BLOBTEXT = 'SL_BLOBTEXT';
  SL_SP_ID = 'SL_SP_ID';

  BP_TEXT = 'BP_TEXT';
  BP_IT_ID = 'BP_IT_ID';
  BP_DELETE = 'BP_DELETE';
  BP_BI_ID = 'BP_BI_ID';
  BP_USEPW = 'BP_USEPW';

  BB_EBENE = 'BB_EBENE';
  BB_BP_ID  = 'BB_BP_ID';
  BB_DELETE = 'BB_DELETE';

  BI_TYP = 'BI_TYP';
  BI_BILD = 'BI_BILD';
  BI_ERWEITERUNG = 'BI_ERWEITERUNG';
  BI_DELETE = 'BI_DELETE';

  ZP_TEXT = 'ZP_TEXT';
  ZP_DELETE = 'ZP_DELETE';
  ZP_BI_ID = 'ZP_BI_ID';

  BS_EBENE = 'BS_EBENE';
  BS_ZP_ID  = 'BS_ZP_ID';
  BS_BB_ID  = 'BS_BB_ID';
  BS_DELETE = 'BS_DELETE';


  SE_HEADER  = 'SE_HEADER';
  SE_BODY    = 'SE_BODY';
  SE_PFAD    = 'SE_PFAD';
  SE_PFADFTP = 'SE_PFADFTP';
  SE_PW      = 'SE_PW';
  SE_DELETE  = 'SE_DELETE';
  SE_HEADERHEIGHT = 'SE_HEADERHEIGHT';
  SE_HEADER_ANZEIGEN = 'SE_HEADER_ANZEIGEN';
  SE_FTPUEBERTRAGEN = 'SE_FTPUEBERTRAGEN';
  SE_HEADER_SEARCH  = 'SE_HEADER_SEARCH';
  SE_BODY_SEARCH    = 'SE_BODY_SEARCH';
  SE_PFADGDRIVE = 'SE_PFADGDRIVE';
  SE_GDRIVEUEBERTRAGEN = 'SE_GDRIVEUEBERTRAGEN';

  VS_SE_ID = 'VS_SE_ID';
  VS_EBENE = 'VS_EBENE';
  VS_BS_ID = 'VS_BS_ID';
  VS_DELETE = 'VS_DELETE';

  SY_BEZ = 'SY_BEZ';
  SY_KEY = 'SY_KEY';
  SY_VALUE1 = 'SY_VALUE1';
  SY_BLOB1  = 'SY_BLOB1';
  SY_BLOB2  = 'SY_BLOB2';
  SY_BLOB3  = 'SY_BLOB3';

  DO_BEZ = 'DO_BEZ';
  DO_DATEINAME = 'DO_DATEINAME';
  DO_EXT = 'DO_EXT';
  DO_PFAD = 'DO_PFAD';
  DO_DELETE = 'DO_DELETE';
  DO_SAVE_FP = 'DO_SAVE_FP';
  DO_SAVE_FTP = 'DO_SAVE_FTP';
  DO_SAVE_CLOUD = 'DO_SAVE_CLOUD';
  DO_PFADGDRIVE = 'DO_PFADGDRIVE';

  SD_SE_ID = 'SD_SE_ID';
  SD_DO_ID = 'SD_DO_ID';
  SD_DELETE = 'SD_DELETE';

  BE_VORNAME  = 'BE_VORNAME';
  BE_NACHNAME = 'BE_NACHNAME';
  BE_LOGIN    = 'BE_LOGIN';
  BE_PW       = 'BE_PW';
  BE_DELETE   = 'BE_DELETE';

  PF_NAME = 'PF_NAME';
  PF_PC = 'PF_PC';
  PF_BE_ID = 'PF_BE_ID';
  PF_HEIGHT = 'PF_HEIGHT';
  PF_WIDTH = 'PF_WIDTH';
  PF_LEFT = 'PF_LEFT';
  PF_TOP = 'PF_TOP';
  PF_WINDOWSTATE = 'PF_WINDOWSTATE';
  PF_DELETE = 'PF_DELETE';

  SK_SE_ID = 'SK_SE_ID';
  SK_SE_ID_LINK = 'SK_SE_ID_LINK';
  SK_DO_ID = 'SK_DO_ID';
  SK_VERLINKT = 'SK_VERLINKT';
  SK_DELETE = 'SK_DELETE';

  KS_SE_ID = 'KS_SE_ID';
  KS_SE_ID_LINK = 'KS_SE_ID_LINK';
  KS_TYP = 'KS_TYP';
  KS_DELETE = 'KS_DELETE';



implementation

end.
