unit ObBusinessClasses;

interface

type
  TNotificationType = (ntobSystem, ntobCoreData, ntobSettings, ntobForms, ntobBearb,
                       ntobStatus, ntobFrames, ntObChangeItems);
  TNotificationTypes = set of TNotificationType;

const
  NTA_UNASSIGNED = -1;
  NTD_UNASSIGNED = 0;

  NTA_SYSTEM_IDLE = 1;

  NTA_FRAME_SPRACHE = 100;
  NTA_FRAME_TEXTE = 101;
  NTA_AKTUAL = 102;
  NTA_CHANGEBUTTONID = 103;
  NTA_EIGENSCHAFTENCLICK = 104;
  NTA_DELETECLICK = 105;

  NTA_SETTINGS_DATABASE = 200;

  NTA_DASH_NEU = 300;
  NTA_DASH_SPEICHERN = 301;
  NTA_DASH_LOESCHEN = 302;
  NTA_DASH_ABBRECHEN = 303;
  NTA_DASH_FOLDERRETURN = 304;
  NTA_DASH_DATAEXPORT = 305;
  NTA_DASH_DATAIMPORT = 306;
  NTA_DASH_SYSTEMEINSTELLUNG = 307;

  NTA_SHOW_BILDER = 400;
  NTA_CLICK_BILD = 401;
  NTA_BAUM_VISIBLE = 402;
  NTA_SHOW_ZWEIGPROP_NEU = 403;
  NTA_SHOW_ZWEIGPROP_BEARB = 404;
  NTA_BAUMEBENE_CHANGED = 405;
  NTA_BAUMZWEIG_CHANGED = 406;
  NTA_FILEOPENDIALOG = 407;
  NTA_DELETEPOS = 408;
  NTA_SEITE_SPERREN = 409;
  NTA_SEITE_SPEICHERN = 410;
  NTA_DOKUMENTREFRESH = 411;
  NTA_LINK_START=412;
  NTA_LINK_ADD=413;
  NTA_LINK_ENTF=414;
  NTA_LINK_ADD_DOK=415;
  NTA_LINK_ADD_DOK_DO=416;
  NTA_LINK_DEL_DOK_DO=417;
  NTA_DOKU_ROW_CHANGED=418;
  NTA_SHOW_HIGHLIGHTERCONFIG=419;

  NTA_TABELLE_SEITE = 1000;
  NTA_SYNTAXHIGHLIGHTERCHANGE=1001;




  {
  NTA_SYSCOMMAND_HELLO = 100;
  NTA_SYSCOMMAND_CLOCK = 110;

  NTA_SETTINGS_HOURS = 200;
  NTA_SETTINGS_PATHS = 210;
  NTA_SETTINGS_ADROBJ = 220;
  NTA_SETTINGS_ADRREC = 221;
  NTA_SETTINGS_CHANGED = 223;
  }

implementation

end.
