program DokuOrga;

uses
  Forms,
  fnt_DokuOrga in 'fnt_DokuOrga.pas' {frm_DokuOrga},
  o_DBReorg in '..\..\DBReorg\o_DBReorg.pas',
  u_RegIni in '..\..\Allgemein\Units\u_RegIni.pas',
  fnt_Splash in 'fnt_Splash.pas' {frm_Splash},
  o_sysobj in '..\Allgemein\o_sysobj.pas',
  ObServerClient in '..\..\Allgemein\ObServer\ObServerClient.pas',
  ObServerUtils in '..\..\Allgemein\ObServer\ObServerUtils.pas',
  o_sysakt in '..\Allgemein\o_sysakt.pas',
  ObBusinessClasses in '..\Allgemein\ObBusinessClasses.pas',
  o_DataTrans in '..\DBExport\o_DataTrans.pas',
  e_SysSpracheList in '..\DBExport\e_SysSpracheList.pas',
  o_DBGuid_Base in '..\DBObj\Base\o_DBGuid_Base.pas',
  o_DBObj in '..\DBObj\Base\o_DBObj.pas',
  o_DBObjExt in '..\DBObj\Base\o_DBObjExt.pas',
  o_DBObjList in '..\DBObj\Base\o_DBObjList.pas',
  o_Sprache_Base in '..\DBObj\Base\o_Sprache_Base.pas',
  o_SysSprache_Base in '..\DBObj\Base\o_SysSprache_Base.pas',
  o_DBGuid_BaseStruk in '..\DBObj\BaseStruk\o_DBGuid_BaseStruk.pas',
  o_Sprache_BaseStruk in '..\DBObj\BaseStruk\o_Sprache_BaseStruk.pas',
  o_Sprache_BaseStrukList in '..\DBObj\BaseStruk\o_Sprache_BaseStrukList.pas',
  o_SysSprache_BaseStruk in '..\DBObj\BaseStruk\o_SysSprache_BaseStruk.pas',
  o_SysSprache_BaseStrukList in '..\DBObj\BaseStruk\o_SysSprache_BaseStrukList.pas',
  o_DBField in '..\Komponenten\DBFields\o_DBField.pas',
  o_DBFieldList in '..\Komponenten\DBFields\o_DBFieldList.pas',
  o_DBGuid in '..\DBObj\o_DBGuid.pas',
  o_Sprache in '..\DBObj\o_Sprache.pas',
  o_SpracheList in '..\DBObj\o_SpracheList.pas',
  o_SysSprache in '..\DBObj\o_SysSprache.pas',
  o_SysSpracheList in '..\DBObj\o_SysSpracheList.pas',
  c_DBTypes in '..\Allgemein\c_DBTypes.pas',
  c_Types in '..\Allgemein\c_Types.pas',
  o_sysfolderlocation in '..\..\Allgemein\Units\o_sysfolderlocation.pas',
  u_System in '..\..\Allgemein\Units\u_System.pas',
  u_dm in '..\Allgemein\u_dm.pas' {dm: TDataModule},
  fr_Base in '..\Frame\fr_Base.pas' {frm_Base: TFrame},
  of_Base in 'of_Base.pas',
  fr_DashToolbar in '..\Frame\fr_DashToolbar.pas' {fra_DashToolbar: TFrame},
  of_DashToolbar in '..\Frame\of_DashToolbar.pas',
  fntMessageDialog in '..\..\Allgemein\Messagebox\fntMessageDialog.pas' {frm_MessageDialog},
  o_Msg in '..\Allgemein\o_Msg.pas',
  o_btnOrdner in '..\Komponenten\o_btnOrdner.pas',
  of_Ordner in '..\Frame\of_Ordner.pas',
  fnt_DialogBase in 'fnt_DialogBase.pas' {frm_DialogBase},
  fnt_OrdnerProp in 'fnt_OrdnerProp.pas' {frm_OrdnerProp},
  of_OrdnerProp in 'of_OrdnerProp.pas',
  o_ItemList_Base in '..\DBObj\Base\o_ItemList_Base.pas',
  o_ItemList_BaseStruk in '..\DBObj\BaseStruk\o_ItemList_BaseStruk.pas',
  o_ItemList in '..\DBObj\o_ItemList.pas',
  o_SprachList_Base in '..\DBObj\Base\o_SprachList_Base.pas',
  o_SprachList_BaseStruk in '..\DBObj\BaseStruk\o_SprachList_BaseStruk.pas',
  o_SprachList in '..\DBObj\o_SprachList.pas',
  o_ItemList_BaseStrukList in '..\DBObj\BaseStruk\o_ItemList_BaseStrukList.pas',
  o_ItemListList in '..\DBObj\o_ItemListList.pas',
  o_SprachList_BaseStrukList in '..\DBObj\BaseStruk\o_SprachList_BaseStrukList.pas',
  o_SprachListList in '..\DBObj\o_SprachListList.pas',
  o_Ordnertyp in '..\DBObj\o_Ordnertyp.pas',
  o_OrdnertypList in '..\DBObj\o_OrdnertypList.pas',
  c_TypesEvent in '..\Allgemein\c_TypesEvent.pas',
  o_ButtonProp_Base in '..\DBObj\Base\o_ButtonProp_Base.pas',
  o_ButtonProp_BaseStruk in '..\DBObj\BaseStruk\o_ButtonProp_BaseStruk.pas',
  o_ButtonProp in '..\DBObj\o_ButtonProp.pas',
  o_ButtonProp_BaseStrukList in '..\DBObj\BaseStruk\o_ButtonProp_BaseStrukList.pas',
  o_ButtonPropList in '..\DBObj\o_ButtonPropList.pas',
  o_BaumButton_Base in '..\DBObj\Base\o_BaumButton_Base.pas',
  o_BaumButton_BaseStruk in '..\DBObj\BaseStruk\o_BaumButton_BaseStruk.pas',
  o_BaumButton in '..\DBObj\o_BaumButton.pas',
  o_BaumButton_BaseStrukList in '..\DBObj\BaseStruk\o_BaumButton_BaseStrukList.pas',
  o_BaumButtonList in '..\DBObj\o_BaumButtonList.pas',
  o_Bilder_Base in '..\DBObj\Base\o_Bilder_Base.pas',
  o_Bilder_BaseStruk in '..\DBObj\BaseStruk\o_Bilder_BaseStruk.pas',
  o_Bilder in '..\DBObj\o_Bilder.pas',
  o_Bilder_BaseStrukList in '..\DBObj\BaseStruk\o_Bilder_BaseStrukList.pas',
  o_BilderList in '..\DBObj\o_BilderList.pas',
  fnt_Bilder in 'fnt_Bilder.pas' {frm_Bilder},
  of_Bilder in 'of_Bilder.pas',
  o_DBFieldBmp in '..\Komponenten\DBFields\o_DBFieldBmp.pas',
  o_DBFieldIco in '..\Komponenten\DBFields\o_DBFieldIco.pas',
  o_DBFieldPng in '..\Komponenten\DBFields\o_DBFieldPng.pas',
  o_DBFieldJpg in '..\Komponenten\DBFields\o_DBFieldJpg.pas',
  fr_Ordner in '..\Frame\fr_Ordner.pas' {fra_Ordner: TFrame},
  o_ZweigProp_Base in '..\DBObj\Base\o_ZweigProp_Base.pas',
  o_ZweigProp_BaseStruk in '..\DBObj\BaseStruk\o_ZweigProp_BaseStruk.pas',
  o_ZweigProp in '..\DBObj\o_ZweigProp.pas',
  o_ZweigProp_BaseStrukList in '..\DBObj\BaseStruk\o_ZweigProp_BaseStrukList.pas',
  o_ZweigPropList in '..\DBObj\o_ZweigPropList.pas',
  o_BaumStruk_Base in '..\DBObj\Base\o_BaumStruk_Base.pas',
  o_BaumStruk_BaseStruk in '..\DBObj\BaseStruk\o_BaumStruk_BaseStruk.pas',
  o_BaumStruk in '..\DBObj\o_BaumStruk.pas',
  o_BaumStruk_BaseStrukList in '..\DBObj\BaseStruk\o_BaumStruk_BaseStrukList.pas',
  o_BaumStrukList in '..\DBObj\o_BaumStrukList.pas',
  fr_Zweig in '..\Frame\fr_Zweig.pas' {fra_Zweig: TFrame},
  of_Zweig in '..\Frame\of_Zweig.pas',
  fnt_ZweigProp in 'fnt_ZweigProp.pas' {frm_ZweigProp},
  of_ZweigProp in 'of_ZweigProp.pas',
  fnt_Zweig in 'fnt_Zweig.pas' {frm_Zweig},
  fnt_DataExport in 'fnt_DataExport.pas' {frm_DataExport},
  of_DataExport in 'of_DataExport.pas',
  e_BilderList in '..\DBExport\e_BilderList.pas',
  fr_Seite in '..\Frame\fr_Seite.pas' {fra_Seite: TFrame},
  fr_SeiteInhalt in '..\Frame\fr_SeiteInhalt.pas' {fra_SeiteInhalt: TFrame},
  of_SeiteInhalt in '..\Frame\of_SeiteInhalt.pas',
  o_Seite_Base in '..\DBObj\Base\o_Seite_Base.pas',
  o_Seite_BaseStruk in '..\DBObj\BaseStruk\o_Seite_BaseStruk.pas',
  o_Seite in '..\DBObj\o_Seite.pas',
  o_Seite_BaseStrukList in '..\DBObj\BaseStruk\o_Seite_BaseStrukList.pas',
  o_SeiteList in '..\DBObj\o_SeiteList.pas',
  o_Seiteverbinden_Base in '..\DBObj\Base\o_Seiteverbinden_Base.pas',
  o_Seiteverbinden_BaseStruk in '..\DBObj\BaseStruk\o_Seiteverbinden_BaseStruk.pas',
  o_Seiteverbinden in '..\DBObj\o_Seiteverbinden.pas',
  tbStringGrid in '..\..\..\Komponenten\MyComponents\tbStringGrid\tbStringGrid.pas',
  o_Systemeinstellung_Base in '..\DBObj\Base\o_Systemeinstellung_Base.pas',
  o_Systemeinstellung_BaseStruk in '..\DBObj\BaseStruk\o_Systemeinstellung_BaseStruk.pas',
  o_Systemeinstellung in '..\DBObj\o_Systemeinstellung.pas',
  o_SyField in '..\Komponenten\o_SyField.pas',
  o_Einstellung in '..\Allgemein\o_Einstellung.pas',
  fnt_Systemeinstellung in 'fnt_Systemeinstellung.pas' {frm_Systemeinstellung},
  of_Systemeinstellung in 'of_Systemeinstellung.pas',
  of_konf_base in '..\Frame\Konfig\of_konf_base.pas',
  of_konf_dokumente in '..\Frame\Konfig\of_konf_dokumente.pas',
  fr_Dokumente in '..\Frame\fr_Dokumente.pas' {fra_Dokumente: TFrame},
  of_Dokumente in '..\Frame\of_Dokumente.pas',
  c_AllgTypes in '..\..\Allgemein\Units\c_AllgTypes.pas',
  of_SeiteEinstellung in '..\Frame\of_SeiteEinstellung.pas',
  fr_SeiteEinstellung in '..\Frame\fr_SeiteEinstellung.pas' {fra_SeiteEinstellung: TFrame},
  fr_konf_base in '..\Frame\Konfig\fr_konf_base.pas' {fra_Konf_Base: TFrame},
  fr_konf_dokumente in '..\Frame\Konfig\fr_konf_dokumente.pas' {fra_Konf_Dokumente: TFrame},
  fr_DokumenteToolbar in '..\Frame\fr_DokumenteToolbar.pas' {fra_DokumenteToolbar: TFrame},
  of_DokumenteToolbar in '..\Frame\of_DokumenteToolbar.pas',
  o_Dokument_Base in '..\DBObj\Base\o_Dokument_Base.pas',
  o_Dokument_BaseStruk in '..\DBObj\BaseStruk\o_Dokument_BaseStruk.pas',
  o_Dokument in '..\DBObj\o_Dokument.pas',
  o_Dokument_BaseStrukList in '..\DBObj\BaseStruk\o_Dokument_BaseStrukList.pas',
  o_DokumentList in '..\DBObj\o_DokumentList.pas',
  o_SeiteDokument_Base in '..\DBObj\Base\o_SeiteDokument_Base.pas',
  o_SeiteDokument_BaseStruk in '..\DBObj\BaseStruk\o_SeiteDokument_BaseStruk.pas',
  o_SeiteDokument in '..\DBObj\o_SeiteDokument.pas',
  o_SeiteDokument_BaseStrukList in '..\DBObj\BaseStruk\o_SeiteDokument_BaseStrukList.pas',
  o_SeiteDokumentList in '..\DBObj\o_SeiteDokumentList.pas',
  fnt_Dialog in 'fnt_Dialog.pas' {frm_Dialog},
  of_Dialog in 'of_Dialog.pas',
  fnt_DialogDokumentBez in 'fnt_DialogDokumentBez.pas' {frm_DialogDokumentBez},
  o_fileicon in '..\Allgemein\o_fileicon.pas',
  o_fileicons in '..\Allgemein\o_fileicons.pas',
  o_Benutzer_Base in '..\DBObj\Base\o_Benutzer_Base.pas',
  o_Benutzer_BaseStruk in '..\DBObj\BaseStruk\o_Benutzer_BaseStruk.pas',
  o_Benutzer_BaseStrukList in '..\DBObj\BaseStruk\o_Benutzer_BaseStrukList.pas',
  o_BenutzerList in '..\DBObj\o_BenutzerList.pas',
  fr_konf_masterpw in '..\Frame\Konfig\fr_konf_masterpw.pas' {fra_Konf_MasterPW: TFrame},
  of_konf_masterpw in '..\Frame\Konfig\of_konf_masterpw.pas',
  o_Benutzer in '..\DBObj\o_Benutzer.pas',
  fnt_MasterPW in 'fnt_MasterPW.pas' {frm_MasterPW},
  fnt_Passwort in 'fnt_Passwort.pas' {frm_Passwort},
  of_Passwort in 'of_Passwort.pas',
  fnt_Passwort_festlegen in 'fnt_Passwort_festlegen.pas' {frm_Passwort_festlegen},
  of_Passwort_festlegen in 'of_Passwort_festlegen.pas',
  e_DokumentList in '..\DBExport\e_DokumentList.pas',
  e_SeiteList in '..\DBExport\e_SeiteList.pas',
  e_SeitedokumentList in '..\DBExport\e_SeitedokumentList.pas',
  e_Itemlist in '..\DBExport\e_Itemlist.pas',
  e_ButtonpropList in '..\DBExport\e_ButtonpropList.pas',
  e_BaumbuttonList in '..\DBExport\e_BaumbuttonList.pas',
  e_ZweigpropList in '..\DBExport\e_ZweigpropList.pas',
  e_BaumstrukList in '..\DBExport\e_BaumstrukList.pas',
  e_SeiteverbindenList in '..\DBExport\e_SeiteverbindenList.pas',
  o_Seiteverbinden_BaseStrukList in '..\DBObj\BaseStruk\o_Seiteverbinden_BaseStrukList.pas',
  o_SeiteverbindenList in '..\DBObj\o_SeiteverbindenList.pas',
  e_SprachlistList in '..\DBExport\e_SprachlistList.pas',
  e_GuidList in '..\DBExport\e_GuidList.pas',
  o_deletebaum in '..\Allgemein\o_deletebaum.pas',
  fr_konf_seite in '..\Frame\Konfig\fr_konf_seite.pas' {fra_Konf_Seite: TFrame},
  of_konf_seite in '..\Frame\Konfig\of_konf_seite.pas',
  u_Allgfunc in '..\..\Allgemein\Units\u_Allgfunc.pas',
  o_Propertyform_Base in '..\DBObj\Base\o_Propertyform_Base.pas',
  o_Propertyform_BaseStruk in '..\DBObj\BaseStruk\o_Propertyform_BaseStruk.pas',
  o_Propertyform in '..\DBObj\o_Propertyform.pas',
  o_Propertyform_BaseStrukList in '..\DBObj\BaseStruk\o_Propertyform_BaseStrukList.pas',
  o_PropertyformList in '..\DBObj\o_PropertyformList.pas',
  fr_konf_ftp in '..\Frame\Konfig\fr_konf_ftp.pas' {fra_Konf_Ftp: TFrame},
  of_konf_ftp in '..\Frame\Konfig\of_konf_ftp.pas',
  o_EinstellungFTP in '..\Allgemein\o_EinstellungFTP.pas',
  fnt_Progress in 'fnt_Progress.pas' {frm_Progress},
  fnt_Link in 'fnt_Link.pas' {frm_Link},
  of_Link in 'of_Link.pas',
  o_SeiteDokumentLink_Base in '..\DBObj\Base\o_SeiteDokumentLink_Base.pas',
  o_SeiteDokumentLink_BaseStruk in '..\DBObj\BaseStruk\o_SeiteDokumentLink_BaseStruk.pas',
  o_SeiteDokumentLink in '..\DBObj\o_SeiteDokumentLink.pas',
  o_SeiteDokumentLink_BaseStrukList in '..\DBObj\BaseStruk\o_SeiteDokumentLink_BaseStrukList.pas',
  o_SeiteDokumentLinkList in '..\DBObj\o_SeiteDokumentLinkList.pas',
  o_SeiteLink_Base in '..\DBObj\Base\o_SeiteLink_Base.pas',
  o_SeiteLink_BaseStruk in '..\DBObj\BaseStruk\o_SeiteLink_BaseStruk.pas',
  o_SeiteLink in '..\DBObj\o_SeiteLink.pas',
  o_SeiteLink_BaseStrukList in '..\DBObj\BaseStruk\o_SeiteLink_BaseStrukList.pas',
  o_SeiteLinkList in '..\DBObj\o_SeiteLinkList.pas',
  fnt_Link_Entf in 'fnt_Link_Entf.pas' {frm_Link_Entf},
  Vcl.Themes,
  Vcl.Styles,
  fr_konf_datenbank in '..\Frame\Konfig\fr_konf_datenbank.pas' {fra_Konf_Datenbank: TFrame},
  of_konf_datenbank in '..\Frame\Konfig\of_konf_datenbank.pas',
  fnt_login in 'fnt_login.pas' {frm_Login},
  o_EinstellungGoogleDrive in '..\Allgemein\o_EinstellungGoogleDrive.pas',
  fr_konf_googledrive in '..\Frame\Konfig\fr_konf_googledrive.pas' {fra_Konf_GoogleDrive: TFrame},
  of_konf_googledrive in '..\Frame\Konfig\of_konf_googledrive.pas',
  o_GoogleDrive in '..\Komponenten\o_GoogleDrive.pas',
  fr_GDriveBaum in '..\Frame\fr_GDriveBaum.pas' {fra_GDriveBaum: TFrame},
  fnt_GDriveBaum in 'fnt_GDriveBaum.pas' {frm_GDriveBaum},
  fr_GDriveBaum2 in '..\Frame\fr_GDriveBaum2.pas' {fra_GDriveBaum2: TFrame},
  o_DragAndDropDataAdapter in '..\Allgemein\o_DragAndDropDataAdapter.pas',
  o_DokumentGridIcon in '..\Allgemein\o_DokumentGridIcon.pas',
  o_DokumentGridIconList in '..\Allgemein\o_DokumentGridIconList.pas',
  fnt_SyntaxHighlighterConfig in '..\SyntaxHighlighter\fnt_SyntaxHighlighterConfig.pas' {frm_SyntaxHighlighterConfig},
  o_xmlsh_BereichList in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_BereichList.pas',
  o_xmlsh_BereichNode in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_BereichNode.pas',
  o_xmlsh_FontNode in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_FontNode.pas',
  o_xmlsh_KommentarList in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_KommentarList.pas',
  o_xmlsh_KommentarNode in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_KommentarNode.pas',
  o_xmlsh_StylenameList in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_StylenameList.pas',
  o_xmlsh_StylenameNode in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlsh_StylenameNode.pas',
  o_xmlshobj in '..\SyntaxHighlighter\XMLSyntaxHighlighter\o_xmlshobj.pas',
  o_fontobj in '..\SyntaxHighlighter\o_fontobj.pas',
  o_styleobj in '..\SyntaxHighlighter\o_styleobj.pas',
  o_syntaxhighlighter in '..\SyntaxHighlighter\o_syntaxhighlighter.pas',
  fnt_SyntaxHighlighterEdit in '..\SyntaxHighlighter\fnt_SyntaxHighlighterEdit.pas' {frm_SyntaxHighlighterEdit},
  fnt_Kommentar in '..\SyntaxHighlighter\fnt_Kommentar.pas' {frm_Kommentar},
  fnt_SyntaxHighlighter in '..\SyntaxHighlighter\fnt_SyntaxHighlighter.pas' {frm_SyntaxHighlighter},
  o_xmlHighlighter in '..\SyntaxHighlighter\o_xmlHighlighter.pas';

{$R *.res}


begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Amethyst Kamri');
  Application.CreateForm(Tfrm_DokuOrga, frm_DokuOrga);
  Application.CreateForm(Tdm, dm);
  Application.Run;
end.
